### ISSUE TITLE
"self-events are not yet supported" are not supported by reh()

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#14]
self-events should be allowed, ands be removed with a warning (as default choice).

**Comment by jupepis** [comment]
Self-events can be supported from remify in the next release. But this change has to happen in parallel with remstats  (@mlmeijerink ) that should understand from the attribute `attr(reh,”self_events”)` whether the sequence has self-events (the attribute assumes value `TRUE`) or not (the attribute assumes value `FALSE`).

**Comment by mlmeijerink** [comment]
Hi, this may take a while to be supported in remstats because I would need to check for every statistic how to deal with self-to-self events.

**Comment by jupepis** [comment]
I close this issue because the suggestion is going to be integrated into the new version of the package (`remify 3.0.0`)

Self-events will be removed during processing, and a warning will inform the user of their presence (and removal). The processed event sequence will have a number of events smaller than the one in the original sequence.
