### ISSUE TITLE
suggestion for omit_dyad argument

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#27]
In the case of long reh's and/or large (sparse) networks, it would be useful to fit a rem using a riskset that only consists of the observed dyads. So if the argument 'omit_dyad' is (for instance) set to "inactive", then all inactive dyads would automatically be omitted in the riskset. An extension that could be interesting is to allow the possibility that is changed for different periods (e.g., because the active network is different in the summer than in the fall). I will also post this in remstats.

**Comment by jomulder** [comment]
Hi Giuseppe, thanks for this. I also like the suggestion to simplify this for users. Maybe the names of the 'values' of the argument could be changed to (respectively) "full", "active", and "manual", referring to all dyads of the full network being at risk, the dyads of the active part of the network being at risk, and thirdly, the current flexible manual specification of the riskset.

Btw, I was wondering whether this will also be workable for an aom as the specification of the riskset on a dyadic level causes the size of the risk set of the receiver to be potentially different for every sender, which may cause problems if the stats etc are stored in (balanced) arrays (with 'full' dimensions). I also reported this in remstats. I am not sure though whether this is an actual issue (if not, sorry for bugging you in this case).

**Comment by jupepis** [comment]
@jomulder , I like the suggestion of a new input argument (_[optional]_) `riskset` that can be defined  `'active'` or `'manual'`  (otherwise if the argument `riskset` is not provided [is `NULL`] it will consider the `'full'` riskset by default).

The current `omit_dyad` argument works already with **aom** and indeed when the riskset is "reduced", having full dimension array may result in a waste of memory.

However, I want to implement this new `riskset` argument in a future version of remify after the upcoming `3.0.0` (perhaps in the `3.1.0`?) because all this can affect the way `remstats`(@mlmeijerink ) and `remstimate` work with `remify` objects and there is little time before the deadline I set for the new version of `remify` to be out.

**Comment by jomulder** [comment]
Related to this point, I think it would be useful if there is a `manual_include` and a `manual_exclude` instead of only exclude. For example, a user may be interested in a specific subset of the network and then it may be not ideal that instead only the excluded dyads can be specified, instead of the ones that one wishes to include.

Another related suggestion, it would be nice if it can be specified which dyads are included/excluded and, alternatively, also which actors are included/excluded, thus either based on a dyadic level or on an actor level.

**Comment by jupepis** [comment]
This improvement will be part of `remify 3.1.0`.
