### ISSUE TITLE
Make naming edgelist columns 'actor1' and 'actor2' not mandatory

### ISSUE THREAD

**Issue by reck0ner** [TilburgNetworkGroup/remify#3]

**Comment by jupepis** [comment]
I would keep the edgelist as a dataframe with named columns for two reasons:

1. the edgelist is also seen as a list at Rcpp level and the access to named columns (list elements) simplifies the use of the input inside the Rcpp functions.
2. we want the user to provide the event sequence in a tidy format that follows simple rules as the named columns
3. the user will have to follow simple indications to defined the input edgelist and won't have to work around solutions for specific cases (I explain some of them below)


If I think  of a solution where names of the data.frame edgelist should not matter, I  would impose a mandatory  order of the columns in the input edgelist. Therefore, I expect that the column order of the input edgelist will follow the order as [time,actor1,actor2,type,weight], for instance, I always expect that on the first column there is the time variable and in the third the type of events, and so forth.

This could be integrated in remify. However, when the type is not defined but weight is, the user will still have to follow the order of the columns and provide an empty fourth column to make the fifth column be the weight column.

Another solution would be to change the input argument edgelist into multiple input arguments as `time`, `actor1`, `actor2`, `type`, `weight` among the arguments of the `remify::reh()`. In this case user will still have to be careful when provide the correct column of actor1 and actor2. This solution will increase the risk to provide swapped dyads as input, but it is the solution that I would like more than the one above based on the column order.

Finally, I think that the two possible solutions that I presented above would still impose the user to learn how to provide input in specific contexts of the network and they can also increase the chances of errors that also the function cannot `remify::reh()` understand (e.g., when actor1 and actor2 are provided in a swapped order).

I close this issue with this comment. However, since it was labeled as enhancement, please, feel free to open a new issue if you have new ideas on this topic.
