### ISSUE TITLE
Installing

### ISSUE THREAD

**Issue by mshafieek** [TilburgNetworkGroup/remify#30]
Hi, 

thanks for the packages.

I cannot install remify and thereafter remstats. I encountered the following error which I do not think, it is related to the R/Rstudio version.

ld: warning: directory not found for option '-L/opt/gfortran/lib/gcc/aarch64-apple-darwin20.0/12.2.0'
ld: warning: directory not found for option '-L/opt/gfortran/lib'
ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [remify.so] Error 1
ERROR: compilation failed for package ‘remify’
* removing ‘/Library/Frameworks/R.framework/Versions/4.3-arm64/Resources/library/remify’
Warning message:
In i.p(...) :
  installation of package ‘/var/folders/jm/d2dwldk11rd7g9mfn2l_7m4c0000gp/T//Rtmpad7mnU/file1953904aea7/remify_3.0.0.tar.gz’ had non-zero exit status

**Comment by jupepis** [comment]
Hi @mshafieek ,

Do you have gcc installed? If not, I suggest you to install it because other R packages around might require it

you can check the version of gcc from your terminal with

`gcc --version`

If you do not have 'gcc' you can install it via Homebrew

`brew install gcc`

If you have 'gcc' and you still get that error, the problem may be in your `~.R/Makevars` file where you set up the flags for the compiler.

Since you are on a Mac, I also suggest you keep 'Xcode' always updated to the latest version.


Best,
Giuseppe
