### ISSUE TITLE
reason for model argument?

### ISSUE THREAD

**Issue by jomulder** [TilburgNetworkGroup/remify#33]
Does the remify object do something different when setting the model to "tie" or "actor". This seems not to be the case... If so, maybe it would be better to omit this argument, and that this choice is made when running remstats.

**Comment by jupepis** [comment]
@jomulder , the reason why we included a model argument in remify is because the function processes the riskset differently based on the modeling approach and also the riskset output object differs between the tie-oriented and the actor-oriented modeling. The riskset object inside a remify output also affects the use of remstats functions that will only allow for certain effects if the model is tie-oriented, or actor-oriented.

**Comment by jomulder** [comment]
Check!

**Comment by jupepis** [comment]
I close this issue.
